### PR TITLE
Update README.md to clarify plugin/opensearch version sync OLD

### PR DESCRIPTION
**Pull request by jeroenhabets**
See NOTE: under Compatibility Matrix

As requested by @lukas-vlcek in  #197

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
@jeroenhabets Looking good. Maybe we can make it even more precise and point to [plugins documentation here](https://opensearch.org/docs/latest/install-and-configure/plugins/#available-plugins) that also further explains the relation wrt to "sub"-patch plugin version, ie. all plugins `2.9.0.x` will work only with OpenSearch `2.9.0`.

Oh, and please provide DCO (--signoff), see https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/issues/78

> Each commit must include a DCO which looks like this
>
> Signed-off-by: Jane Smith <jane.smith@email.com>
>
> You may type this line on your own when writing your commit messages. However, if your user.name and user.email are set in your git configs, you can use `-s` or `--signoff` to add the Signed-off-by line to the end of the commit message.

**Review by lukas-vlcek — CHANGES_REQUESTED** [review]
@jeroenhabets The only thing that is holding this PR back is that the commit is missing DCO. In technical terms this means that when you do `git commit` you need to include `-s` or `--signoff` (given you setup your `user.name` and `user.email` props in git config) **OR** you simply include the `Signed-off-by: Jane Smith [jane.smith@email.com](mailto:jane.smith@email.com)` into the commit message manually (git `-s` command does it for your). See my other comment on the PR about this.

On top of that you can consider adding the info about how the plugin "sub"-patch version fits here as well. But that is just a nice-to-have. (Again, check my previous comment under the PR.)

Thanks for your work. Looking forward to the PR update :-)

**Comment by jeroenhabets** [comment]
@lukas-vlcek I just commited an update including a Signed-off-by line.

**Comment by lukas-vlcek** [comment]
@jeroenhabets The first commit is still missing the DCO. Maybe you can merge both commits into a single commit and have only this one commit signed?

**Comment by jeroenhabets** [comment]
Sorry @lukas-vlcek, then it's easier just to redo from start: https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/pull/204

**Pull request closed without merging**
