### PR TITLE
Upgrade to OpenSearch 1.3.2

### PR DESCRIPTION
**Pull request by greut**
https://github.com/opensearch-project/OpenSearch/releases/tag/1.3.2
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-1.3.2.md

### CODE REVIEW

**Comment by vinylen** [comment]
Waiting for this :)

**Comment by lukas-vlcek** [comment]
@greut Thanks for this PR. The only bit holding the PR back now is missing DCO.

Please see https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin

As explained in the doc ^^ you can add the certificate either manually in commit message or use [sign-off commit parameter](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s).

**Comment by greut** [comment]
@lukas-vlcek alrighty then.

**Review by lukas-vlcek — APPROVED** [review]

**Comment by lukas-vlcek** [comment]
Thanks @greut

**Pull request merged**
