### PR TITLE
enable GitHub dependabot

### PR DESCRIPTION
**Pull request by rursprung**
this will (partially) automate dependency updates. dependabot will create PRs if a dependency can be updated automatically. see the [dependabot documentation][docs] for further information.

solves #149

note: as always with dependabot config there isn't any easy way to test this, so this is untested (it's actually the first time i'm setting it up for a gradle project! with other projects it worked fine so far).

[docs]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
@rursprung Thanks for PR.

@reta Do you have any experience with dependabot in OpenSearch that would be worth sharing in this context?

**Comment by lukas-vlcek** [comment]
@rursprung Did you consider that right now we are maintaining two branches?: `main` and `v1.3`. I can imagine it would make sense to run the bot against both the branches. I think by default it runs only against the default (i.e `main`) branch, see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch

We also have a `mixin` branch but that is a different story.

**Comment by rursprung** [comment]
> @rursprung Did you consider that right now we are maintaining two branches?: `main` and `v1.3`. I can imagine it would make sense to run the bot against both the branches. I think by default it runs only against the default (i.e `main`) branch, see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch
> 
> We also have a `mixin` branch but that is a different story.

i've now added the `v1.3` branch for GHA + gradle updates and `mixin` for the GHA updates. it's a setup i hadn't considered before (my GH repos usually only ever have one active branch) and i somehow naively presumed that dependabot would work on the file in the branch (and check all branches) rather than always checking the default branch... 


as for the DCO check: adding
```yaml
if: ${{ github.actor != 'dependabot[bot]' }}
```
to it (on all branches) _should_ do the trick. but i'd suggest to give it a spin first and only do this in a follow-up step after the first PR(s) land as this will have to be done on all branches.

**Review by lukas-vlcek — APPROVED** [review]
LGTM

Thanks!

**Comment by lukas-vlcek** [comment]
It seems we got a bunch of new upgrade PRs as a result 😄

**Comment by lukas-vlcek** [comment]
And all of the upgrade PRs are now merged or resolved in some way. Uff.... 😓
I think the dependabot works nice and proved to be useful 👍

**Pull request merged**
