### PR TITLE
[#184] upgrade to OpenSearch 2.8.0

### PR DESCRIPTION
**Pull request by grechaw**
This PR prepares the plugin for use with OpenSearch 2.8.0

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
@grechaw Thanks for PR, can you please just sign the commit?

Excerpt from [CONTRIBUTING.md](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin)

> Each commit must include a DCO which looks like this
>
>
> Signed-off-by: Jane Smith <jane.smith@email.com>
>
>
> You may type this line on your own when writing your commit messages. However, if your user.name and user.email are set in your git configs, you can use -s or – – signoff to add the Signed-off-by line to the end of the commit message.

**Comment by sastorsl** [comment]
`git commit -S --amend` in you topic `v2.8.0` bransh and push again will fix that for you.

**Comment by lukas-vlcek** [comment]
Yup, `push -f`

**Comment by grechaw** [comment]
My mistake -- I should have read the contributing document more carefully.  I've amended the commit.  Thanks for the good work on this plugin!

**Comment by lukas-vlcek** [comment]
I need to prepare better issue template with this fact highlighted. Thanks!

**Comment by lukas-vlcek** [comment]
Not sure what is wrong with the build here, I will check no Monday.
Happy weekend!

**Comment by lukas-vlcek** [comment]
The issue is with java version support

```
Caused by: java.io.IOException: Failed to process the entry 'META-INF/versions/19/com/fasterxml/jackson/core/io/doubleparser/FastDoubleSwar.class' from '/Users/lukas.vlcek/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.15.1/241c054ba8503de092a12acad9f083dd39935cc0/jackson-core-2.15.1.jar'
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:161)
        at org.gradle.internal.classpath.ClasspathWalker.visitJarContents(ClasspathWalker.java:91)
        at org.gradle.internal.classpath.ClasspathWalker.visit(ClasspathWalker.java:55)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.visitEntries(InstrumentingClasspathFileTransformer.java:148)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$instrument$0(InstrumentingClasspathFileTransformer.java:139)
        at org.gradle.internal.classpath.ClasspathBuilder.buildJar(ClasspathBuilder.java:66)
        at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:53)
        ... 9 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:151)
        ... 15 more
```

I think we will need to upgrade to gradle > 8.x first (issue: #160).

**Comment by lukas-vlcek** [comment]
BTW, @grechaw you can add the following line to the commit message to automatically close the upgrade ticket when this commit is merged:

> Closes #184

**Comment by grechaw** [comment]
Ok we're all set with a rebased commit!

**Review by lukas-vlcek — APPROVED** [review]
LGTM

**Pull request merged**
